spring.application.name=ordenes

spring.datasource.url=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=Oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

server.port=8080